[#ftl]
[@b.head/]
  [@b.grid items=students var="student"]
    [@b.gridbar]
      bar.addItem("初始化", action.multi("billInit"))
    [/@]
    [@b.row]
      [@b.boxcol/]
      [@b.col title="序号" width="5%"]${student_index+1}[/@]
      [@b.col title="学号" property="code" width="11%"/]
      [@b.col title="姓名" property="name" width="11%"/]
      [@b.col title="学制" property="duration" width="7%"/]
      [@b.col title="年级" property="state.grade" width="7%"/]
      [@b.col title="培养层次" property="level.name" width="7%"/]
      [@b.col title="院系" sortable="false" width="15%"][#assign currentStudentState = currentStateMap.get(student)/]${(currentStudentState.department.name)}[/@]
      [@b.col title="专业" sortable="false" ]${(currentStudentState.major.name)!} ${(currentStudentState.direction.name)!}[/@]
      [@b.col title="班级" sortable="false" width="15%"]${(currentStudentState.squad.name)!}[/@]
      [@b.col title="应缴(元)" sortable="false" width="10%"]${((stateTuitionConfigMap.get(currentStudentState).amount / (100.0 *student.duration?ceiling))?string("0.00#"))!"<span style=\"color: red\">收费标准未找到</span>"}[/@]
    [/@]
  [/@]
[@b.foot/]
