[#ftl]
[@b.head/]
    [@b.toolbar title="打印收费配置"]
      bar.addPrint();
      bar.addClose();
    [/@]
[@b.grid items=creditFeeDefaults var="creditFeeDefault"]
  [@b.row]
    [@b.col title="序号"  width="10%"]${creditFeeDefault_index+1}[/@]
    [@b.col title="学历层次" property="level.name" width="30%"/]
    [@b.col title="课程类别" property="courseType.name" width="30%"/]
    [@b.col title="学费（分/元）" property="value" width="30%"]${(creditFeeDefault.value?string("0.00"))!"0.00"}[/@]
  [/@]
[/@]
[@b.foot/]
