[#ftl]
[@b.head/]
  [@b.toolbar title="支付配置"]
    bar.addBack();
  [/@]
  [@b.grid items=feeTypeConfigs var="feeTypeConfig"]
    [@b.gridbar]
      bar.addItem("${b.text("action.add")}", action.add());
    [/@]
    [@b.row]
      [@b.boxcol/]
      [@b.col title="收费类型" property="feeType.name"  width="10%"/]
      [@b.col title="产品ID" property="productId" width="15%"/]
      [@b.col title="密钥" property="secret" width="70%"/]
    [/@]
  [/@]
[@b.foot/]
