[#ftl]
[@b.head/]
  [@b.toolbar title="<span style=\"color:blue\">" + semester.schoolYear + "</span>学年<span style=\"color:blue\">" + semester.name + "</span>学期<span style=\"color:blue\">" + bills?first.std.state.department.name + "</span>欠费明细（共<span style=\"color:blue;padding-left: 3px;padding-right:3px\">" + bills?size + "</span>条记录）"]
    bar.addClose();
  [/@]
  [@b.grid items=bills var="bill" sortable="false"]
    [@b.row]
      [@b.col title="序号" width="7%"]${bill_index + 1}[/@]
      [@b.col title="学号" width="13%" property="std.user.code"/]
      [@b.col title="姓名" width="12%" property="std.user.name"/]
      [@b.col title="年级" width="10%" property="std.state.grade"/]
      [@b.col title="专业" width="15%" property="std.state.major.name"/]
      [@b.col title="班级" width="20%" property="std.state.squad.name"/]
      [@b.col title="收费类型" width="10%" property="feeType.name"/]
      [@b.col title="应缴" width="13%" property="amount"]${(bill.amount?string("0.00#"))!}[/@]
    [/@]
  [/@]
[@b.foot/]
