[#ftl]
[@b.head/]
  [@b.toolbar title="<span style=\"color:blue\">" + bills?first.semester.beginOn?string("yyyy") + "</span>学年度<span style=\"color:blue\">" + bills?first.std.state.department.name + "</span>欠费明细（共<span style=\"color:blue;padding-left: 3px;padding-right:3px\">" + bills?size + "</span>条记录）"]
    bar.addClose();
  [/@]
  [@b.grid items=bills var="bill" sortable="false"]
    [@b.row]
      [@b.col title="序号" width="70px"]${bill_index + 1}[/@]
      [@b.col title="学号" property="std.code"/]
      [@b.col title="姓名" property="std.name"/]
      [@b.col title="年级" property="std.state.grade" width="70px"/]
      [@b.col title="专业" property="std.state.major.name"/]
      [@b.col title="班级" property="std.state.squad.name"/]
      [@b.col title="收费类型" property="type.name"/]
      [@b.col title="应缴" property="shouldPay"]${(bill.shouldPay?string("0.00#"))!}[/@]
    [/@]
  [/@]
[@b.foot/]
