[#ftl]
[@b.head/]
  [@b.grid items=bills var="bill"]
    [@b.gridbar]
      bar.addItem("${b.text("action.modify")}", action.edit());
      bar.addItem("${b.text("action.info")}", action.info());
    [/@]
    [@b.row]
      [@b.boxcol/]
      [@b.col title="学号" property="std.user.code" width="10%"/]
      [@b.col title="姓名" property="std.user.name" width="8%"/]
      [@b.col title="年级" property="std.state.grade"  width="7%"/]
      [@b.col title="学历层次" property="std.level.name" width="7%"/]
      [@b.col title="院系" property="std.state.department.name"  width="9%" ]${bill.std.state.department.shortName!bill.std.state.department.name}[/@]
      [@b.col title="专业" property="std.state.major.name"  width="20%" /]
      [@b.col title="收费类型" property="feeType.name"  width="8%"/]
      [@b.col title="应缴" property="amount"  width="7%"]<span[#if bill.amount?default(0) lt 1] style="color: red"[/#if]>${((bill.amount/100.0)?string("0.00#"))!}</span>[/@]
      [@b.col title="实缴" property="payed"  width="7%"]<span[#if bill.payed?default(0) lt 1] style="color: red"[/#if]>${((bill.payed/100.0)?string("0.00#"))!}</span>[/@]
      [@b.col title="实缴时间" property="payAt"  width="12%"]${(bill.payAt?string("yy-MM-dd HH:mm"))!}[/@]
    [/@]
  [/@]
[@b.foot/]
